-
    environment:
      matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"
    build: false
    install:
      - .ci/appveyor/install.bat
    test_script:
      - .ci/appveyor/test.bat
    after_test:
      - .ci/appveyor/after.bat

-
    environment:
      matrix:
        - PYTHON: "C:\\Python35"
    build: false
    install:
      - .ci/appveyor/install.bat
    test_script:
      - .ci/appveyor/test.bat

